### ISSUE TITLE
Why do you use custom file (jsonl)

### ISSUE THREAD

**Issue by FaustinM** [JustComments/jc-server#1]
JSON is more simple to use with nodeJS

**Comment by OrKoN** [comment]
http://jsonlines.org/ allows append only writing

**Comment by FaustinM** [comment]
Yes but we can use native require function for use json. JsonLines is more complicate to use and there are not a lot of advantages! When we want to remove a comment require is more simple and more optimize.

<details><p>
Sorry for my English, I'm french :)
</p></details>
